language: julia

branches:
  only:
  - master
  - workab

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.5
  - nightly

jobs:
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'using Pkg;cd(Pkg.dir("LevelDB")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
