name = "LevelDB"
uuid = "6248df61-47b1-58fa-9b7c-c0f1183480ca"
authors = ["jerryzhenleicai@users.noreply.github.com", "Guido Kraemer <gdkrmr@users.noreply.github.com>"]
version = "3.0.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
LevelDB_jll = "e5add9ea-9f03-521a-be84-f8c1bde3cbe9"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
